### ISSUE TITLE
Stage 4!

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-object-values-entries#14]
## ~~Stage 4~~
- [x] committee approval
- [x] Implement in two browsers https://github.com/tc39/proposal-object-values-entries/issues/10
- [x] significant in-the-field experience
- [x] test262 tests ([PR](https://github.com/tc39/test262/pull/453))
## ~~Stage 3~~
- [x] committee approval
- [x] spec editor signoff https://github.com/tc39/proposal-object-values-entries/issues/9
- [x] spec reviewer signoff https://github.com/tc39/proposal-object-values-entries/issues/8
## ~~Stage 2~~
- [x] committee approval
- [x] spec text written
- [x] spec reviewers selected
